'''
Created on Jan 15, 2014

@author: nonlinear
'''

MAX_NAME_PRICE_DISTANCE = 20
MAX_PRICE_NAME_DISTANCE = 10
MAX_PRICE_PRICE_DISTANCE = 4
MAX_BUTTON_PRICE_DISTANCE = 10
MAX_PRICE_BUTTON_DISTANCE = 20

PAGES_TO_FIND_REPEATING_TITLE_PART = 10

PAGES_FOR_SCHEMA_RETRIEVAL_NO = 10

DIFFERENT_PRICE_VALS_FACTOR = 0.3

