#various
http://shop.nordstrom.com/
http://shop.nordstrom.com/c/stores?origin=tab
http://shop.nordstrom.com/c/personal-stylists?cm_sp=merch-_-corp_0218personalstylist-_-storelocator_info
http://shop.nordstrom.com/c/nordstrom-stylist-customer-testimonials?cm_sp=swp-_-corp_personalstylist-_-personalstylistlp_testimonials
http://shop.nordstrom.com/c/nordstrom-gift-cards?origin=header-top-promo
http://shop.nordstrom.com/c/gift-cards
http://shop.nordstrom.com/c/olivia-kim?dept=8000001&origin=topnav&cm_sp=merch-_-corp_0424popin-_-swpnav_ok
http://shop.nordstrom.com/c/nordstrom-blogs?dept=8000001&origin=topnav&cm_sp=merch-_-corp_0424popin-_-swpnav_blog
#category
http://shop.nordstrom.com/c/recommendations/?origin=tab
http://shop.nordstrom.com/c/mens-tshirts?dept=8000001&origin=topnav
http://shop.nordstrom.com/c/mens-big-tall-clothing?dept=8000001&origin=topnav
http://shop.nordstrom.com/c/mens-sunglasses?dept=8000001&origin=topnav
http://shop.nordstrom.com/c/mens-oxfords?dept=8000001&origin=topnav
http://shop.nordstrom.com/c/womens-skirts?dept=8000001&origin=topnav
#product
http://shop.nordstrom.com/s/zella-live-in-reversible-leggings/3035710?origin=recommendation-3035710-60153599-1-1-18-RR&PageCategoryId=LP:%20All%20Products%20%3E%20Get%20Recommendations%20(60153599)
http://shop.nordstrom.com/s/pleione-mixed-media-tunic-regular-petite/3736370?origin=recommendation-3736370-60153599-1-2-18-RR&PageCategoryId=LP:%20All%20Products%20%3E%20Get%20Recommendations%20(60153599)
http://shop.nordstrom.com/s/lucky-brand-garment-washed-henley-online-only/3753163?origin=category-personalizedsort&contextualcategoryid=0&fashionColor=Charcoal+Grey&resultback=400&cm_sp=personalizedsort-_-browseresults-_-1_1_A
http://shop.nordstrom.com/s/alternative-trim-fit-heathered-raglan-henley/3782278?origin=category
http://shop.nordstrom.com/s/kid-dangerous-hood-lincoln-t-shirt/3826005?origin=category
http://shop.nordstrom.com/s/boss-hugo-boss-james-trim-fit-navy-wool-blazer/3749543?origin=fashionresultspreview
http://shop.nordstrom.com/s/david-donahue-royal-oxford-regular-fit-dress-shirt/3233680?origin=fashionresultspreview
http://shop.nordstrom.com/s/ted-baker-london-linnoo-trim-fit-linen-blend-sport-shirt/3568455?origin=fashionresultspreview
http://shop.nordstrom.com/s/ray-ban-classic-clubmaster-51mm-sunglasses/3142275?origin=category-personalizedsort&contextualcategoryid=0&fashionColor=&resultback=400&cm_sp=personalizedsort-_-browseresults-_-1_1_A
http://shop.nordstrom.com/s/tom-ford-snowdon-50mm-sunglasses/3545131?origin=category
http://shop.nordstrom.com/s/kw-jazz-55mm-sunglasses/3170132?origin=category
http://shop.nordstrom.com/s/timberland-boot-company-wodehouse-lost-history-cap-toe-oxford-men/3797997?origin=category-personalizedsort&contextualcategoryid=0&fashionColor=Dark+Brown&resultback=360&cm_sp=personalizedsort-_-browseresults-_-1_1_A
http://shop.nordstrom.com/s/ted-baker-london-rogrr-cap-toe-oxford-men/3562174?origin=category
http://shop.nordstrom.com/s/painted-threads-print-pleat-maxi-skirt-juniors/3744285?origin=category-personalizedsort&contextualcategoryid=0&fashionColor=Navy+Print&resultback=560&cm_sp=personalizedsort-_-browseresults-_-1_1_B
http://shop.nordstrom.com/s/michael-kors-bradshaw-chronograph-bracelet-watch-43mm-nordstrom-exclusive/3758841?origin=category-personalizedsort&contextualcategoryid=0&fashionColor=&resultback=1508&cm_sp=personalizedsort-_-browseresults-_-1_3_B
http://shop.nordstrom.com/s/michael-kors-baisley-crystal-bezel-chronograph-bracelet-watch-41mm-nordstrom-exclusive/3726042?origin=category
//TEST
http://shop.nordstrom.com/s/lush-floral-print-woven-skater-skirt-juniors/3739826?origin=category
http://shop.nordstrom.com/c/rag-bone?dept=8000001&origin=topnav
http://shop.nordstrom.com/c/womens-watches-shop?dept=8000001&origin=topnav
http://shop.nordstrom.com/s/michael-kors-baisley-crystal-bezel-chronograph-bracelet-watch-41mm-nordstrom-exclusive/3762960?origin=category