#various
http://www.kickz.com/uk/
http://www.kickz.com/uk/support/static/help_returns
http://www.kickz.com/uk/support/static/help_safety
http://www.kickz.com/uk/support/home-man
http://www.kickz.com/uk/support/static/store_mobile
http://www.kickz.com/uk/support/home-woman
#category
http://www.kickz.com/uk/fulltext/air+max+1/PRICE_ASC/c
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=289.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Schuhe&selectedSizeUnitValue=EU&selSecLvlcatgs=basketball+retro&selSecLvlcatgs=basketball+schuhe&selLowPrice=89&selHighPrice=90
http://www.kickz.com/uk/catalog/search?lastClick=GENDER&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=289.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Schuhe&selectedSizeUnitValue=EU&selSecLvlcatgs=boots&selLowPrice=39&selHighPrice=289
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=289.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Schuhe&selectedSizeUnitValue=EU&selSecLvlcatgs=asics+running&selSecLvlcatgs=ellesse+running&selSecLvlcatgs=running&selLowPrice=25&selHighPrice=140
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=289.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Schuhe&selectedSizeUnitValue=EU&selSecLvlcatgs=espandrillos&selSecLvlcatgs=sandalen+und+flip+flops&selLowPrice=8&selHighPrice=31
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=289.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Schuhe&selectedSizeUnitValue=EU&selSecLvlcatgs=skate&selLowPrice=9&selHighPrice=289
http://www.kickz.com/uk/men/shoes/classics-low,converse-chucks,fashion,limited-editions,Nike-Air-Force-1,Nike-Air-Max,retro-schuhe,running,running-funktion,running-retro,skate,sneakers-high,sneakers-low/c
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=1000.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selTopCatgs=Stuff&selSecLvlcatgs=kopfh%C3%B6rer&selLowPrice=2&selHighPrice=1000
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=1000.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selTopCatgs=Stuff&selSecLvlcatgs=lautsprecher&selLowPrice=19&selHighPrice=400
#product
http://www.kickz.com/uk/asics-sneakers-low-gel-lyte-3-black_white-105426249
http://www.kickz.com/uk/vans-skate-old-skool-vintage_grape_wine-100485127
http://www.kickz.com/uk/vans-skate-authentic-slim-pop_patriot_blue_cordovan-104255161
http://www.kickz.com/uk/vans-skate-authentic-star_wars_yoda_aloha-100387145
http://www.kickz.com/uk/vans-skate-era-59-suede_denim_black_chili_pepper-100392122
http://www.kickz.com/uk/vans-skate-era-van_doren_camo_white_checker-100483133
http://www.kickz.com/uk/beats-by-dre-headphones-lady-gaga-heartbeats-black-black-113874903
http://www.kickz.com/uk/beats-by-dre-headphones-studio-2_0-white-white-113868305
http://www.kickz.com/uk/beats-by-dre-headphones-lady-gaga-heartbeats-white-white-113874904
http://www.kickz.com/uk/beats-by-dre-headphones-urbeats-2-purple-purple-113876204
http://www.kickz.com/uk/beats-by-dre-headphones-tour-2_0-white-white-113871404
http://www.kickz.com/uk/marshall-headphones-marshall-monitor-black-937919999
http://www.kickz.com/uk/lowdi-loudspeakers-one-speaker-with-bluetooth-blue-938240111
http://www.kickz.com/uk/nixon-loudspeakers-blaster-black_multiskin-108866089
http://www.kickz.com/uk/x-mini-loudspeakers-x-mini-rave-with-fm-radio-black-937748001
http://www.kickz.com/uk/x-mini-loudspeakers-x-mini-max-2-white-937746100
http://www.kickz.com/uk/beats-by-dre-loudspeakers-beatbox-portable-black-106385001
http://www.kickz.com/uk/beats-by-dre-loudspeakers-beatbox-portable-white-106385100
//TEST
http://www.kickz.com/uk/catalog/search?lastClick=GENDER&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=600.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selGenders=M&selTopCatgs=Bekleidung&selSecLvlcatgs=college+jacken&selSecLvlcatgs=jacken&selSecLvlcatgs=windbreaker&selLowPrice=19&selHighPrice=600
http://www.kickz.com/uk/catalog/search?lastClick=CATEGORY&pager.currentPage=1&pager.size=64&sorting=DATE_ADDED&filterReset=&campId=&queryString=&topLimitDoublePrice=1000.0&priceIgnored=true&priceSetByUser=false&lastBrand=&lastCatg=&selTopCatgs=accessoires&selTopCatgs=Stuff&selSecLvlcatgs=energy+drinks&selLowPrice=2&selHighPrice=1000
http://www.kickz.com/uk/jordan-jackets-flight-future-remix-jacket-black_blue_grey-114559010
http://www.kickz.com/uk/jordan-jackets-flight-future-remix-jacket-black_black_red-114559011
http://www.kickz.com/uk/carhartt-t-shirts-waterloo-t-shirt-white_black-114019290