#various
http://www.citysports.com/Westfield-City-Sports-Store.aspx
http://www.citysports.com/RacquetServices.aspx
http://www.citysports.com/shippingoptions.aspx
http://www.citysports.com/Bethesda-City-Sports-Store.aspx
http://www.citysports.com/Downtown-Crossing-City-Sports-Store.aspx
http://www.citysports.com/Insider/
#category
http://www.citysports.com/Tennis-Footwear/Search
http://www.citysports.com/womens-pants-and-capris/Search
http://www.citysports.com/bags/search
http://www.citysports.com/City-Sports-Tees/search
http://www.citysports.com/Mens-Running-Shoes/search
http://www.citysports.com/Womens-Running-Footwear/search
http://www.citysports.com/Mens-Trail-Running-Footwear/search
#product
http://www.citysports.com/Patagonia-Refugio-Pack-28L-Backpack/223136/Product
http://www.citysports.com/Jansport-Houston-Backpack/227727/Product
http://www.citysports.com/The-North-Face-Rucksack-Backpack/227021/Product
http://www.citysports.com/The-North-Face-Recon-Backpack---Womens/227049/Product
http://www.citysports.com/City-Sports-Classic-Tee---Womens/230750/Product
http://www.citysports.com/City-Sports-Classic-Tee---Womens/230742/Product
http://www.citysports.com/City-Sports-Classic-Tee---Mens/230707/Product
http://www.citysports.com/City-Sports-2014-Boston-Strong-Tee---Mens/231401/Product
http://www.citysports.com/Salomon-X-Scream---Mens/230595/Product
http://www.citysports.com/Salomon-X-Tour---Mens/230731/Product
http://www.citysports.com/Five-Ten-Rogue-VCS-Climbing-Shoes---Mens/230974/Product
//TEST
http://www.citysports.com/Womens-Training-Jackets/search
http://www.citysports.com/Womens-Training-Jackets/Blue/580/search
http://www.citysports.com/Hoka-One-One-Clifton---Mens/230400/Product
http://www.citysports.com/Saucony-Kinvara-5---Mens/228479/Product
http://www.citysports.com/ASICS-GEL-Noosa-Tri-9---Mens/223724/Product